documentation
Julia-ivv/shortener-url pull request #18
Opened 2024-01-30 09:38 UTC by Julia-ivv

2024-02-02 01:59 UTC, capsulated requested changes
Необходимо пару пакетов вынести из `internal`. Хорошие кандидаты для этого - это компрессор и, скажем, частично функционал аунтификатора. Их перенести в папку `pkg`, что отлично будет выглядеть в документации в example_test.go

Остальное всё ок: бенчмарки, отсортированные иморты и комментарии для документации

Чуть подробнее в комментариях

2024-02-02 01:59 UTC, capsulated commented on cmd/shortener/data.json
В `.gitignore` файлик добавлен, но он всё равно остался в репозитории. Если он нужен для тестов или бенчмарков - его можно оставить

2024-02-02 01:59 UTC, capsulated commented on internal/app/authorizer/auth_errors.go
нейминг файла можно оставить просто `authorizer/errors.go`, так как понятно, что ошибки относятся к этому пакету

2024-02-02 01:59 UTC, capsulated commented on internal/app/authorizer/tools.go
>  func GenerateRandomInt(max int) (int, error) {
Этот функционал можно вынести из `internal`, скажем, в тот же `pkg` и для него, как раз, документация и `example_test.go` будут актуальны

2024-02-02 01:59 UTC, capsulated commented on internal/app/compressing/compressing.go
Компрессор, также, лучше вынести из internal в корень, либо в `pkg`.

Можно сделать так: посмотреть какой функционал дублируется и в инкрементах и в выпускном проекте gofermart. И дублирующиеся пакеты перенести в pkg. В следующем выпускном проекте можно их импортировать

2024-02-02 01:59 UTC, capsulated commented on internal/app/handlers/example_test.go
> +func ExampleHandlers_PostURL() {
Для `internal` документация актуальна только для программистов - это только комментарии. `example_test.go` будет актуален только для внешних пакетов, а для internal это даже лишнее. Обычно создают `examples` пакет в корне

Фиксить, в принципе, не надо, но принять к сведению обязательно. Главное, понимать подход

2024-02-02 01:59 UTC, capsulated commented on internal/app/storage/doc.go
Это, скорее, лишнее. Всё же лучше удалить этот файл. Может я что-то не так понял, тогда жду ответ на комментарий

2024-02-02 07:21 UTC, Julia-ivv commented on internal/app/compressing/compressing.go
В пакете middleware дублируется не все, можно вынести в pkg часть пакета? И тогда можно его в pkg назвать тоже middleware?

2024-02-02 07:25 UTC, Julia-ivv commented on internal/app/storage/doc.go
В теории написано, что если в пакете несколько .go-файлов, нужно создать отдельный файл doc.go, в котором будет информация о пакете. Если doc.go удалить, в какой из файлов писать общий комментарий для пакета? В каждый? Или достаточно в какой-то один?

2024-02-05 20:13 UTC, capsulated commented on internal/app/storage/doc.go
Можно оставить, да, чтобы не дублировать. Но реальных проектах редко такое встречал. Так что ок, оставляем)

2024-02-05 20:14 UTC, capsulated approved these changes
Всё отлично! 👍

2024-02-05 20:24 UTC, merged